# ===================================================================
# Основные настройки сервера
# ===================================================================
server:
  port: 8080 # Порт, на котором будет работать приложение
  error:
    # Включать stacktrace в ответ об ошибке только при наличии параметра `trace=true`
    include-stacktrace: on_param

# ===================================================================
# Настройки Spring Boot
# ===================================================================
spring:
  application:
    name: rag-ollama-service # Имя приложения, используется в логах и метриках
  lifecycle:
    # Таймаут для корректного завершения работы приложения
    timeout-per-shutdown-phase: 30s

  # Настройки Web MVC
  mvc:
    async:
      # Таймаут для асинхронных запросов (@Async, CompletableFuture в контроллерах).
      # Должен быть больше, чем самый долгий таймаут в Resilience4j (120s).
      request-timeout: 130s

  # Настройки пулов потоков для асинхронных задач
  task:
    execution:
      pool:
        core-size: 4
        max-size: 10
      shutdown:
        await-termination: true
        await-termination-period: 30s
    scheduling:
      shutdown:
        await-termination: true
        await-termination-period: 30s

  # --- Настройки подключения к базе данных (PostgreSQL) ---
  datasource:
    url: jdbc:postgresql://localhost:5432/ragdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  # --- Настройки JPA и Hibernate ---
  jpa:
    # `validate`: проверять схему БД на соответствие сущностям при старте
    hibernate:
      ddl-auto: validate
    show-sql: true # Показывать генерируемые SQL-запросы в логах
    properties:
      hibernate:
        format_sql: true # Форматировать SQL-запросы для лучшей читаемости

  # --- Настройки миграций базы данных Flyway ---
  flyway:
    enabled: true
    locations: classpath:db/migration # Путь к SQL-миграциям

  # --- Настройки кэширования (Caffeine) ---
  cache:
    cache-names:
      - vector_search_results # Кэш для результатов RAG-запросов
      - token_counts # Кэш для подсчета токенов
    caffeine:
      # Настройки кэша: макс. 500 записей, время жизни записи 10 минут
      spec: maximumSize=500,expireAfterWrite=10m

  # ===================================================================
  # Настройки Spring AI
  # ===================================================================
  ai:
    ollama:
      base-url: http://localhost:11434 # URL запущенного сервиса Ollama
      chat:
        options:
          model: llama3 # Модель для генерации текста
          temperature: 0.7 # Уровень "креативности" модели (0.0 - детерминированный, 1.0 - макс. креативный)
          max-tokens: 2048 # Максимальное количество токенов в ответе
      embedding:
        options:
          model: mxbai-embed-large # Модель для создания векторных представлений (эмбеддингов)
    vectorstore:
      pgvector:
        table-name: vector_store # Имя таблицы для хранения векторов
        index-type: HNSW # Тип индекса для быстрого поиска (Hierarchical Navigable Small World)
        distance-type: COSINE_DISTANCE # Метрика для измерения схожести векторов (косинусное расстояние)
        dimensions: 1024 # Размерность вектора (зависит от embedding-модели)

# ===================================================================
# Настройки Actuator для мониторинга (Observability)
# ===================================================================
management:
  endpoints:
    web:
      exposure:
        # Эндпоинты, доступные по HTTP
        include: health, info, prometheus, metrics
  endpoint:
    health:
      # Показывать детали состояния компонентов только авторизованным пользователям (или всегда, если security отключен)
      show-details: when_authorized
  metrics:
    tags:
      # Глобальный тег, который будет добавляться ко всем метрикам
      application: ${spring.application.name}
    distribution:
      # Включить гистограммы для метрики времени ответа HTTP-сервера
      percentiles-histogram:
        http.server.requests: true
      # Определить "корзины" (SLA) для гистограмм времени ответа
      sla:
        http.server.requests: 50ms, 100ms, 200ms, 500ms, 1s, 2s

# ===================================================================
# Настройки OpenAPI / Swagger
# ===================================================================
springdoc:
  api-docs:
    path: /api-docs # Путь к JSON-спецификации OpenAPI
  swagger-ui:
    path: /swagger-ui.html # Путь к интерактивной документации Swagger UI
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

# ===================================================================
# Настройки отказоустойчивости (Resilience4j)
# ===================================================================
resilience4j:
  circuitbreaker:
    instances:
      ollama: # Единственная, правильно названная конфигурация для Ollama
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 15s
        failure-rate-threshold: 60
        event-consumer-buffer-size: 10
  retry:
    instances:
      ollama:
        max-attempts: 2
        wait-duration: 5s
        # Важно: указываем исключения, при которых нужно делать повтор
        retry-on-exception: "org.springframework.web.reactive.function.client.WebClientRequestException, org.springframework.web.client.ResourceAccessException, java.util.concurrent.TimeoutException"
  timelimiter:
    instances:
      ollama:
        timeout-duration: 120s # 2 минуты таймаут для генерации
        cancel-running-future: true

# ===================================================================
# Кастомные настройки приложения
# ===================================================================
app:
  prompt:
    # Путь к шаблону промпта для RAG
    rag-template-path: "prompts/rag-prompt.tmpl"
  reranking:
    enabled: true # Включить/выключить переранжирование
    keyword-match-boost: 0.1 # "Бонус" к релевантности за совпадение ключевого слова
  rate-limiting:
    enabled: true # Включить/выключить ограничение частоты запросов
    limits:
      - endpoint: "/api/v1/rag/query"
        capacity: 10 # 10 запросов
        refill-period-minutes: 1 # за 1 минуту
      - endpoint: "/api/v1/chat"
        capacity: 20
        refill-period-minutes: 1
  tokenization:
    # Модель кодирования для токенизатора.
    # "o200k_base" используется для Llama 3, Mistral.
    # Для моделей OpenAI (GPT-4, GPT-3.5) следует использовать "cl100k_base".
    encoding-model: "o200k_base"
  context:
    # Максимальное количество токенов, выделяемое под контекст из документов.
    # Оставляем запас для системного промпта, вопроса пользователя и генерации ответа.
    # Llama-3 имеет окно 8k, поэтому 4k - безопасный лимит.
    max-tokens: 4096
  chat:
    history:
      # Количество последних сообщений, загружаемых для поддержания контекста
      max-messages: 10
  ingestion:
    scheduler:
      # Задержка между запусками планировщика индексации документов
      delay-ms: 10000 # 10 секунд
  http-client:
    connect-timeout: 10s # Таймаут на установку TCP-соединения
    response-timeout: 120s # Общий таймаут на получение ответа (включая установку соединения)
    read-write-timeout: 120s # Таймаут на чтение/запись отдельных пакетов данных